version: "3.7"
services:

  mysql:
    image: mariadb:10.3.9-bionic
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: promoot
      MYSQL_USER: promoot
      MYSQL_PASSWORD: root

  traefik:
    image: traefik:1.7.18
    command:
      - "--api"
      - "--docker"
      - "--docker.exposedbydefault=false"
    depends_on:
      - backend
    ports:
      - "${port.http}:80"
      - "${port.dashboard}:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  redis:
    image: redis
  
  backend:
    image: skn0tt/promoot-backend:v0.2.0
    restart: on-failure
    depends_on:
      - mysql
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip: /api/"
    environment:
      SMTP_HOST: ${smtp.host}
      SMTP_PASSWORD: ${smtp.password}
      SMTP_PORT: ${smtp.port}
      SMTP_SENDER: ${smtp.sender}
      SMTP_USERNAME: ${smtp.username}
      MAIL_BODY_TEMPLATE: ${event.mail_templatesmplates.body}
      MAIL_SUBJECT_TEMPLATE: ${event.mail_templatesmplates.subject}
      MAIL_TICKET_URL_TEMPLATE: ${host_url}/tickets/{{id}}/checkIn
      MYSQL_DATABASE: promoot
      MYSQL_USERNAME: promoot
      MYSQL_PASSWORD: root
      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: 3306
      MERCHANT_NAMES: ${event.merchants.names}
      MERCHANT_PASSWORDS: ${event.merchants.passwords}
      ADMIN_PASSWORD: ${event.admin_password}
      TICKET_GROUPS: ${event.ticket_groups}
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379

  ui:
    image: skn0tt/promoot-ui:v0.2.0
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip: /"
    environment:
      - TICKET_GROUPS=${event.ticket_groups}
      - MERCHANT_NAMES=${event.merchants.names}
      - TITLE=${event.name}
      - CONFIG_VARS=MERCHANT_NAMES,TICKET_GROUPS,TITLE
