version: "3.7"
services:

  mysql:
    image: mariadb:10.3.9-bionic
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: promoot
      MYSQL_USER: promoot
      MYSQL_PASSWORD: root

  traefik:
    image: traefik:1.7.18
    command:
      - "--api"
      - "--docker"
      - "--docker.exposedbydefault=false"
    depends_on:
      - backend
    ports:
      - "${PORT_HTTP}:80"
      - "${PORT_TRAEFIK_DASHBOARD}:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  redis:
    image: redis
  
  backend:
    image: skn0tt/promoot-backend:v0.1.1
    restart: on-failure
    depends_on:
      - mysql
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip: /api/"
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SENDER: ${SMTP_SENDER}
      SMTP_USERNAME: ${SMTP_USERNAME}
      MAIL_BODY_TEMPLATE: ${MAIL_BODY_TEMPLATE}
      MAIL_SUBJECT_TEMPLATE: ${MAIL_SUBJECT_TEMPLATE}
      MAIL_TICKET_URL_TEMPLATE: ${HOST_URL}/tickets/{{id}}/checkIn
      MYSQL_DATABASE: promoot
      MYSQL_USERNAME: promoot
      MYSQL_PASSWORD: root
      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: 3306
      MERCHANT_NAMES: ${MERCHANT_NAMES}
      MERCHANT_PASSWORDS: ${MERCHANT_PASSWORDS}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      TICKET_GROUPS: ${TICKET_GROUPS}
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379

  ui:
    image: skn0tt/promoot-ui:v0.1.1
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip: /"
    environment:
      - TICKET_GROUPS=${TICKET_GROUPS}
      - MERCHANT_NAMES=${MERCHANT_NAMES}
      - TITLE=${TITLE}
      - CONFIG_VARS=MERCHANT_NAMES,TICKET_GROUPS,TITLE


