port:
  http: 3000
  dashboard: 8080

host_url: http://localhost

smtp:
  host: smtp.ethereal.email
  password: D5jUQMHSgQmJZJrT8Y
  port: 587
  sender: promoot@simonknott.de
  username: ykpfdkpewa7xdx5q@ethereal.email

event:
  name: Promoot Party
  ticket_groups: "default:reduced:kids"
  merchants:
    names: "Alice:Bob:Carl"
    passwords: "alice:bob:carl"
  admin_password: "root"
  mail_templates:
    body: >-
      Hello {{firstName}},

      you find your ticket attached.

      Greetings,
      Peter Promoot
    subject: Greetings {{firstName}}, your ticket is here!

