ADMIN_PASSWORD: "root"
TICKET_GROUPS: "default:reduced:kids"
MERCHANT_NAMES: "Alice:Bob:Carl"
MERCHANT_PASSWORDS: "alice:bob:carl"
PORT_HTTP: 80
PORT_TRAEFIK_DASHBOARD: 8080
TITLE: "Promoot Party"
SMTP_HOST: smtp.ethereal.email
SMTP_PASSWORD: D5jUQMHSgQmJZJrT8Y
SMTP_PORT: 587
SMTP_SENDER: promoot@simonknott.de
SMTP_USERNAME: ykpfdkpewa7xdx5q@ethereal.email
HOST_URL: http://localhost
MAIL_BODY_TEMPLATE: >-
  Hello {{firstName}},

  you find your ticket attached.

  Greetings,
  Peter Promoot

MAIL_SUBJECT_TEMPLATE: {{firstName}}, your ticket is here!
